// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timeServerMessages.proto

package hu.zsinko.rpctime.proto;

public final class TimeServerMessages {
  private TimeServerMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TimeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hu.zsinko.rpctime.TimeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 current_time = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    boolean hasCurrentTime();
    /**
     * <code>required int64 current_time = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    long getCurrentTime();
  }
  /**
   * Protobuf type {@code hu.zsinko.rpctime.TimeResponse}
   */
  public static final class TimeResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hu.zsinko.rpctime.TimeResponse)
      TimeResponseOrBuilder {
    // Use TimeResponse.newBuilder() to construct.
    private TimeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TimeResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TimeResponse defaultInstance;
    public static TimeResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TimeResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TimeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currentTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.class, hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TimeResponse> PARSER =
        new com.google.protobuf.AbstractParser<TimeResponse>() {
      public TimeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TimeResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CURRENT_TIME_FIELD_NUMBER = 1;
    private long currentTime_;
    /**
     * <code>required int64 current_time = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    public boolean hasCurrentTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 current_time = 1;</code>
     *
     * <pre>
     *server to connect to
     * </pre>
     */
    public long getCurrentTime() {
      return currentTime_;
    }

    private void initFields() {
      currentTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCurrentTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, currentTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, currentTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hu.zsinko.rpctime.TimeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hu.zsinko.rpctime.TimeResponse)
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.class, hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.Builder.class);
      }

      // Construct using hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        currentTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeResponse_descriptor;
      }

      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse getDefaultInstanceForType() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.getDefaultInstance();
      }

      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse build() {
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse buildPartial() {
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse result = new hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currentTime_ = currentTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse) {
          return mergeFrom((hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse other) {
        if (other == hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.getDefaultInstance()) return this;
        if (other.hasCurrentTime()) {
          setCurrentTime(other.getCurrentTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCurrentTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long currentTime_ ;
      /**
       * <code>required int64 current_time = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public boolean hasCurrentTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 current_time = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public long getCurrentTime() {
        return currentTime_;
      }
      /**
       * <code>required int64 current_time = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public Builder setCurrentTime(long value) {
        bitField0_ |= 0x00000001;
        currentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 current_time = 1;</code>
       *
       * <pre>
       *server to connect to
       * </pre>
       */
      public Builder clearCurrentTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hu.zsinko.rpctime.TimeResponse)
    }

    static {
      defaultInstance = new TimeResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hu.zsinko.rpctime.TimeResponse)
  }

  public interface TimeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hu.zsinko.rpctime.TimeRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code hu.zsinko.rpctime.TimeRequest}
   */
  public static final class TimeRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hu.zsinko.rpctime.TimeRequest)
      TimeRequestOrBuilder {
    // Use TimeRequest.newBuilder() to construct.
    private TimeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TimeRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TimeRequest defaultInstance;
    public static TimeRequest getDefaultInstance() {
      return defaultInstance;
    }

    public TimeRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TimeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.class, hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<TimeRequest> PARSER =
        new com.google.protobuf.AbstractParser<TimeRequest>() {
      public TimeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TimeRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hu.zsinko.rpctime.TimeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hu.zsinko.rpctime.TimeRequest)
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.class, hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.Builder.class);
      }

      // Construct using hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.internal_static_hu_zsinko_rpctime_TimeRequest_descriptor;
      }

      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest getDefaultInstanceForType() {
        return hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.getDefaultInstance();
      }

      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest build() {
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest buildPartial() {
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest result = new hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest) {
          return mergeFrom((hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest other) {
        if (other == hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hu.zsinko.rpctime.TimeRequest)
    }

    static {
      defaultInstance = new TimeRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hu.zsinko.rpctime.TimeRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hu_zsinko_rpctime_TimeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hu_zsinko_rpctime_TimeResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hu_zsinko_rpctime_TimeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hu_zsinko_rpctime_TimeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030timeServerMessages.proto\022\021hu.zsinko.rp" +
      "ctime\"$\n\014TimeResponse\022\024\n\014current_time\030\001 " +
      "\002(\003\"\r\n\013TimeRequestB-\n\027hu.zsinko.rpctime." +
      "protoB\022TimeServerMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hu_zsinko_rpctime_TimeResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hu_zsinko_rpctime_TimeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hu_zsinko_rpctime_TimeResponse_descriptor,
        new java.lang.String[] { "CurrentTime", });
    internal_static_hu_zsinko_rpctime_TimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hu_zsinko_rpctime_TimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hu_zsinko_rpctime_TimeRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
