// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timeService.proto

package hu.zsinko.rpctime.proto;

public final class TimeServerServices {
  private TimeServerServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf service {@code hu.zsinko.rpctime.TimeService}
   */
  public static abstract class TimeService
      implements com.google.protobuf.Service {
    protected TimeService() {}

    public interface Interface {
      /**
       * <code>rpc getCurrentTime(.hu.zsinko.rpctime.TimeRequest) returns (.hu.zsinko.rpctime.TimeResponse);</code>
       */
      public abstract void getCurrentTime(
          com.google.protobuf.RpcController controller,
          hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest request,
          com.google.protobuf.RpcCallback<hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new TimeService() {
        @java.lang.Override
        public  void getCurrentTime(
            com.google.protobuf.RpcController controller,
            hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest request,
            com.google.protobuf.RpcCallback<hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse> done) {
          impl.getCurrentTime(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getCurrentTime(controller, (hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getCurrentTime(.hu.zsinko.rpctime.TimeRequest) returns (.hu.zsinko.rpctime.TimeResponse);</code>
     */
    public abstract void getCurrentTime(
        com.google.protobuf.RpcController controller,
        hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest request,
        com.google.protobuf.RpcCallback<hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return hu.zsinko.rpctime.proto.TimeServerServices.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getCurrentTime(controller, (hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest)request,
            com.google.protobuf.RpcUtil.<hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends hu.zsinko.rpctime.proto.TimeServerServices.TimeService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getCurrentTime(
          com.google.protobuf.RpcController controller,
          hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest request,
          com.google.protobuf.RpcCallback<hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.class,
            hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse getCurrentTime(
          com.google.protobuf.RpcController controller,
          hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse getCurrentTime(
          com.google.protobuf.RpcController controller,
          hu.zsinko.rpctime.proto.TimeServerMessages.TimeRequest request)
          throws com.google.protobuf.ServiceException {
        return (hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          hu.zsinko.rpctime.proto.TimeServerMessages.TimeResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:hu.zsinko.rpctime.TimeService)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021timeService.proto\022\021hu.zsinko.rpctime\032\030" +
      "timeServerMessages.proto2`\n\013TimeService\022" +
      "Q\n\016getCurrentTime\022\036.hu.zsinko.rpctime.Ti" +
      "meRequest\032\037.hu.zsinko.rpctime.TimeRespon" +
      "seB0\n\027hu.zsinko.rpctime.protoB\022TimeServe" +
      "rServices\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          hu.zsinko.rpctime.proto.TimeServerMessages.getDescriptor(),
        }, assigner);
    hu.zsinko.rpctime.proto.TimeServerMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
